baseURL = 'https://www.jangio.net/'
locale = 'en-us'
title = 'jangio.net'

[params]
  description = "Technology, Linux, hardware, photography, personal projects."
  dateFormat = "2006-01-02"


[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
name = "Home"
identifier = "home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Posts"
identifier = "posts"
pageRef = "/posts"
weight = 2

[[menu.main]]
name = "Projects"
identifier = "projects"
pageRef = "/projects"
weight = 3

[[menu.main]]
name = "About"
identifier = "about"
pageRef = "/about"
weight = 4
